// Constants
module.exports = Object.freeze({
    DEFAULT_SIGN: '-',
    REDACTION_PLACEHOLDER: 'redacted',
    ENV_LOG_SENSITIVE_CONNECTION_DATA: 'LOG_SENSITIVE_CONNECTION_DATA',
    ENV_LOG_REMOTE_USER: 'LOG_REMOTE_USER',
    ENV_LOG_REFERER: 'LOG_REFERER'
});